"""empty message

Revision ID: 0076151f8c62
Revises: a5cffa318ac2
Create Date: 2025-04-21 11:56:52.822678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0076151f8c62'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id_specie', sa.Integer(), nullable=False),
    sa.Column('name_specie', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_specie')
    )
    op.create_table('vehicles',
    sa.Column('id_vehicle', sa.Integer(), nullable=False),
    sa.Column('name_vehicle', sa.String(length=50), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_vehicle')
    )
    op.create_table('planets',
    sa.Column('id_planet', sa.Integer(), nullable=False),
    sa.Column('name_planet', sa.String(length=100), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('gravity', sa.Integer(), nullable=True),
    sa.Column('planet_specie', sa.Integer(), nullable=False),
    sa.Column('planet_vehicle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_specie'], ['species.id_specie'], ),
    sa.ForeignKeyConstraint(['planet_vehicle'], ['vehicles.id_vehicle'], ),
    sa.PrimaryKeyConstraint('id_planet')
    )
    op.create_table('peoples',
    sa.Column('id_people', sa.Integer(), nullable=False),
    sa.Column('name_people', sa.String(length=100), nullable=False),
    sa.Column('id_homeworld', sa.Integer(), nullable=True),
    sa.Column('specie_people', sa.Integer(), nullable=True),
    sa.Column('vehicle_people', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_homeworld'], ['planets.id_planet'], ),
    sa.ForeignKeyConstraint(['specie_people'], ['species.id_specie'], ),
    sa.ForeignKeyConstraint(['vehicle_people'], ['vehicles.id_vehicle'], ),
    sa.PrimaryKeyConstraint('id_people')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peoples')
    op.drop_table('planets')
    op.drop_table('vehicles')
    op.drop_table('species')
    # ### end Alembic commands ###
